server:
  port: 8010
spring:
  application:
    name: account
  datasource:
    name: library
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 19900310
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.southwind.entity
